brand:
  name: Lasa Bakery
menu-string: Menu

nav:
  - title: Dịch vụ
    url: '#services'
  - title: Bánh
    url: '#portfolio'
  - title: Chúng tôi
    url: '#about'
  # - title: Team
  #   url: '#team'
  - title: Liên hệ
    url: '#contact'

copyright: Copyright &copy; lasabakery.com 2019

social-buttons:
  - icon: fa fa-twitter
    url: '#'
  - icon: fa fa-facebook
    url: '#'
  - icon: fa fa-linkedin
    url: '#'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
